apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: monitoring-scrape-allow
  namespace: agri-dev
spec:
  podSelector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - api-gateway
          - auth-service
          - user-service
          - catalog-service
          - order-service
          - payment-service
          - messaging-service
          - jobs-service
          - delivery-service
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - port: 8080
          protocol: TCP
        - port: 8086
          protocol: TCP
        - port: 8087
          protocol: TCP
        - port: 8088
          protocol: TCP
